version: '3'

volumes:
  data_counter:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONF_PATH: configs/app_conf_docker.yml
    restart: always
    environment:
      GIT_HASH: $GIT_HASH
    ports:
      - 58213:8000
    volumes:
      - data_counter:/var/lib/marketimer
    command: ["/app/marketimer"]
