app_port: 8000
eth_rpc: wss://eth-mainnet.g.alchemy.com/v2/123
arb_rpc: wss://arb-mainnet.g.alchemy.com/v2/123
matic_rpc: wss://polygon-mainnet.g.alchemy.com/v2/123
op_rpc: wss://opt-mainnet.g.alchemy.com/v2/123